### ISSUE TITLE
Gradle logo?

### ISSUE THREAD

**Issue by atomfrede** [jhipster-redesign/jhipster-redesign.github.io#2]
Gradle uses the [new gradlephant](http://gradle.org/what-the-s-is-up-with-the-elephant/) as logo. Should we also update the gradle logo? But I've not found a vector graphics of the [vertical logo](http://gradle.org/wp-content/uploads/2015/10/gradle-logo-vertical-01.jpg) yet.

**Comment by deepu105** [comment]
If you are sure thats the official one then plz change it, png is also
fine, some of the logos are PNG inside img/icons folder

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
updated
