### ISSUE TITLE
Mobile : still not perfect

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster-redesign/jhipster-redesign.github.io#5]
On mobile :
- space at right
- the menu : jhipster-uml is troncated

![screenshot_2016-01-16-09-08-09](https://cloud.githubusercontent.com/assets/9156882/12371381/0c7837e6-bc32-11e5-894c-fda789642f59.png)
![screenshot_2016-01-16-09-08-26](https://cloud.githubusercontent.com/assets/9156882/12371382/0c7ca240-bc32-11e5-8098-1c9a16d91a17.png)

**Comment by deepu105** [comment]
@pascalgrimaud check now, have fixed these and tested in all the options chrome provides for simulation and in my mobiles. seems ok now

for the menu you have to scroll

**Comment by pascalgrimaud** [comment]
Space at right => ok
For menu => troncated the 1st time, after clicking on sub menu, I can scroll

**Comment by pascalgrimaud** [comment]
No it's ok, it was my cache!!
